### ISSUE TITLE
500 after selecting the language

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/wordpress#4]
The following error showed up after selecting to install in portuguese and after hitting submit the install form.
I can login afterwards, but wonder if this has any effect on current instalation.

Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /var/www/html/wp-includes/class-phpmailer.php:946 Stack trace: #0 /var/www/html/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress') #1 /var/www/html/wp-admin/includes/upgrade.php(392): wp_mail('...', 'Novo site WordP...', 'O seu novo site...') #2 /var/www/html/wp-admin/includes/upgrade.php(95): wp_new_blog_notification('', '...', 1, 'A senha que esc...') #3 /var/www/html/wp-admin/install.php(367): wp_install('...', 1, '', '...', 'pt_PT') #4 {main} thrown in /var/www/html/wp-includes/class-phpmailer.php on line 946

**Comment by pierreozoux** [comment]
should be fixed

**Comment by fab286im** [comment]
Hello, i have exactly the same problem. How you fixed this problem ? thank you

**Comment by pierreozoux** [comment]
do a `docker-compose pull`, I updated the docker image: https://github.com/indiehosters/docker-wordpress/commit/38869ccdecbf5de2ba41d913b674dce06c21a102

Let me know if you still see an issue :)
