### ISSUE TITLE
ENV variables example should be on readme.md

### ISSUE THREAD

**Issue by diogocsc** [indiehosters/wordpress#5]
Hi,
I'm trying to follow instructions to get a local dev environment running, but cannot...

It would be nice to have an example of an env file populated here...
Like this (wonder if am missing something
![docker_compose_up_wordpress_indie_env](https://cloud.githubusercontent.com/assets/1706650/18755813/7b5262cc-80e5-11e6-8795-fbf10e2b8076.png)

**Comment by pierreozoux** [comment]
We could add a file called `env-example` to the project.

This file should contain:

```
MYSQL_ROOT_PASSWORD=mystrongpassword
```

Do you want to PR?

**Comment by diogocsc** [comment]
PRed
